var BCEngine={height:0,width:0,cubeSize:0,evnBoxSize:0,playArea:null,player:null,currentSelection:0,map:{}};BCEngine.map.chunk1=null;BCEngine.objects=[];BCEngine.objects[0]={name:"Stone",img:"stone.png",id:"1",strength:"2"};BCEngine.objects[1]={name:"Cobblestone",img:"cobble.png",id:"2",strength:"2"};BCEngine.objects[2]={name:"Dirt",img:"dirt.png",id:"3",strength:"0.5"};BCEngine.objects[3]={name:"Grass",img:"grass.png",id:"4",strength:"0.5"};
BCEngine.objects[4]={name:"Plank",img:"plank.png",id:"5",strength:"1.5"};BCEngine.objects[5]={name:"Brick",img:"brick.png",id:"6",strength:"4"};BCEngine.keyPresses={};BCEngine.keyPresses.isLeft=!1;BCEngine.keyPresses.isRight=!1;BCEngine.utils={};BCEngine.gravity=3;BCEngine.sliding={};BCEngine.sliding.isSliding=!1;BCEngine.sliding.curSpeed=0;BCEngine.sliding.slideDirection="right";BCEngine.blockDestruction={};BCEngine.blockDestruction.lastReferredBlock=null;
BCEngine.blockDestruction.lastRunningTimer=null;BCEngine.eventHandlers={};
BCEngine.createEnvBoxes=function(){BCEngine.evnBoxSize=(BCEngine.height-5*BCEngine.cubeSize)/2;var a=document.createElement("div");a.setAttribute("id","evn1");document.getElementById("envBox").appendChild(a);var c=document.createElement("div");c.setAttribute("id","evn2");document.getElementById("envBox").appendChild(c);var b=document.createElement("div");b.setAttribute("id","evn3");document.getElementById("envBox").appendChild(b);a.style.height=BCEngine.evnBoxSize+"px";c.style.height=BCEngine.evnBoxSize+
"px";b.style.width=BCEngine.width-16*BCEngine.cubeSize+"px"};BCEngine.initPlayArea=function(){BCEngine.playArea=document.getElementById("playBox");BCEngine.playArea.style.height=5*BCEngine.cubeSize+"px";BCEngine.playArea.style.top=BCEngine.evnBoxSize+"px"};
BCEngine.renderChunk=function(a){BCEngine.playArea.innerHTML="";for(var c=0,b=a.length;c<b;c++)for(var d=0,e=a[c].length;d<e;d++){var f=document.createElement("div");BCEngine.playArea.appendChild(f);f.style.width=BCEngine.cubeSize+"px";f.style.height=BCEngine.cubeSize+"px";f.style.top=c*BCEngine.cubeSize+"px";f.style.left=BCEngine.cubeSize*d+"px";f.style.position="absolute";f.setAttribute("horz",c);f.setAttribute("vertz",d);f.setAttribute("blockID",a[c].substr(d,1));if("0"==a[c].substr(d,1))f.style.background=
"lightblue";else{var g=Number(a[c].substr(d,1))-1;f.setAttribute("strength",BCEngine.objects[g].strength);f.style.background="url("+BCEngine.objects[g].img+")";f.style.backgroundRepeat="repeat";f.style.backgroundSize="100% 100%"}}};
BCEngine.initPlayer=function(){var a=document.createElement("div");document.getElementById("playBox").appendChild(a);a.setAttribute("id","player");a.style.width=BCEngine.cubeSize+"px";a.style.height=2*BCEngine.cubeSize+"px";BCEngine.player=document.getElementById("player");setInterval(BCEngine.startPhysics,10)};
BCEngine.startPhysics=function(){var a=window.getComputedStyle(BCEngine.player),c=Number(a.top.substr(0,a.top.length-2)),a=Number(a.left.substr(0,a.left.length-2)),b=c+2*BCEngine.cubeSize,b=BCEngine.utils.ceilFoot(b)-1,d=a+1*BCEngine.cubeSize,d=BCEngine.utils.ceilHori(d)-1,e=BCEngine.map.chunk1[b].substr(d,1),f=BCEngine.map.chunk1[b].substr(d-1,1);if("0"==e&&"0"==f)BCEngine.player.style.top=c+BCEngine.gravity+"px";if(BCEngine.keyPresses.isRight&&0==BCEngine.map.chunk1[b-1].substr(d,1)&&0==BCEngine.map.chunk1[b-
2].substr(d,1))BCEngine.player.style.left=a+BCEngine.gravity+"px";if(BCEngine.keyPresses.isLeft&&0==BCEngine.map.chunk1[b-1].substr(d-1,1)&&0==BCEngine.map.chunk1[b-2].substr(d-1,1))BCEngine.player.style.left=a-BCEngine.gravity+"px";if(BCEngine.sliding.isSliding)BCEngine.sliding.curSpeed-=0.2,1>BCEngine.sliding.curSpeed?BCEngine.sliding.isSliding=!1:"right"==BCEngine.sliding.slideDirection&&0==BCEngine.map.chunk1[b-1].substr(d,1)&&0==BCEngine.map.chunk1[b-2].substr(d,1)?BCEngine.player.style.left=
a+BCEngine.sliding.curSpeed+"px":"left"==BCEngine.sliding.slideDirection&&0==BCEngine.map.chunk1[b-1].substr(d-1,1)&&0==BCEngine.map.chunk1[b-2].substr(d-1,1)?BCEngine.player.style.left=a-BCEngine.sliding.curSpeed+"px":BCEngine.sliding.isSliding=!1};BCEngine.eventHandlers.keyDownEvent=function(a){switch(a.keyCode){case 37:BCEngine.keyPresses.isLeft=!0;break;case 39:BCEngine.keyPresses.isRight=!0}return!1};
BCEngine.eventHandlers.keyUpEvent=function(a){switch(a.keyCode){case 37:BCEngine.keyPresses.isLeft=!1;BCEngine.sliding.isSliding=!0;BCEngine.sliding.curSpeed=3;BCEngine.sliding.slideDirection="left";break;case 39:BCEngine.keyPresses.isRight=!1;BCEngine.sliding.isSliding=!0;BCEngine.sliding.curSpeed=3;BCEngine.sliding.slideDirection="right";break;case 32:BCEngine.player.style.top="0px"}return!1};
BCEngine.removeBlock=function(a){BCEngine.blockDestruction.lastRunningTimer=null;var c=a.getAttribute("horz"),b=a.getAttribute("vertz"),d=BCEngine.map.chunk1[c],e=d.substring(0,b),e=e+"0"+d.substring(Number(b)+1,d.length);BCEngine.map.chunk1[c]=e;a.setAttribute("blockID","0");a.style.background="lightblue";BCEngine.playArea.removeChild(BCEngine.blockDestruction.lastReferredBlock);BCEngine.blockDestruction.lastReferredBlock=null;return!1};
BCEngine.eventHandlers.mouseDownEvent=function(a){if(0==a.button&&(a=a.target||a.srcElement,!(null==a.getAttribute("horz")||null!=BCEngine.blockDestruction.lastReferredBlock||"0"==a.getAttribute("blockID")))){var c=document.createElement("div");c.setAttribute("class","crack");BCEngine.playArea.appendChild(c);var b=window.getComputedStyle(a);c.style.top=b.top;c.style.left=b.left;c.style.width=BCEngine.cubeSize;c.style.height=BCEngine.cubeSize;BCEngine.blockDestruction.lastReferredBlock=c;BCEngine.blockDestruction.lastRunningTimer=
setTimeout(BCEngine.removeBlock,1E3*Number(a.getAttribute("strength")),a)}};BCEngine.eventHandlers.mouseUpEvent=function(){null!=BCEngine.blockDestruction.lastRunningTimer&&clearTimeout(BCEngine.blockDestruction.lastRunningTimer);if(null!=BCEngine.blockDestruction.lastReferredBlock)BCEngine.playArea.removeChild(BCEngine.blockDestruction.lastReferredBlock),BCEngine.blockDestruction.lastReferredBlock=null;return!1};
BCEngine.eventHandlers.rightClickEvent=function(a){a=a.target||a.srcElement;if(null==a.getAttribute("horz")||"0"!=a.getAttribute("blockID"))return!1;var c=a.getAttribute("horz"),b=a.getAttribute("vertz"),d=BCEngine.map.chunk1[c],e=d.substring(0,b),e=e+BCEngine.objects[BCEngine.currentSelection].id,e=e+d.substring(Number(b)+1,d.length);BCEngine.map.chunk1[c]=e;a.setAttribute("blockID",BCEngine.objects[BCEngine.currentSelection].id);a.setAttribute("strength",BCEngine.objects[BCEngine.currentSelection].strength);
a.style.backgroundImage="url("+BCEngine.objects[BCEngine.currentSelection].img+")";a.style.backgroundRepeat="repeat";a.style.backgroundSize="100% 100%";return!1};
BCEngine.eventHandlers.scrollEvent=function(a){if(a.wheelDelta)switch(a=a.wheelDelta/60,a){case 2:BCEngine.currentSelection+=1;if(BCEngine.currentSelection>=BCEngine.objects.length)BCEngine.currentSelection=0;document.title=BCEngine.objects[BCEngine.currentSelection].name;break;case -2:BCEngine.currentSelection-=1;if(-1>=BCEngine.currentSelection)BCEngine.currentSelection=BCEngine.objects.length-1;document.title=BCEngine.objects[BCEngine.currentSelection].name}else switch(a=a.detail,a){case -3:BCEngine.currentSelection+=
1;if(BCEngine.currentSelection>=BCEngine.objects.length)BCEngine.currentSelection=0;document.title=BCEngine.objects[BCEngine.currentSelection].name;break;case 3:BCEngine.currentSelection-=1;if(-1>=BCEngine.currentSelection)BCEngine.currentSelection=BCEngine.objects.length-1;document.title=BCEngine.objects[BCEngine.currentSelection].name}};
window.onload=function(){BCEngine.height=window.innerHeight;BCEngine.width=window.innerWidth;BCEngine.cubeSize=Math.floor(BCEngine.width/16);BCEngine.map.chunk1="0550000000000000 0006000000000000 0006000000000000 4444544444444444 3333333333333333";BCEngine.map.chunk1=BCEngine.map.chunk1.split(" ");BCEngine.createEnvBoxes();BCEngine.initPlayArea();BCEngine.renderChunk(BCEngine.map.chunk1);BCEngine.initPlayer();document.onkeydown=BCEngine.eventHandlers.keyDownEvent;document.onkeyup=BCEngine.eventHandlers.keyUpEvent;
document.addEventListener("mousedown",function(a){BCEngine.eventHandlers.mouseDownEvent(a);return!1},!1);document.addEventListener("mouseup",BCEngine.eventHandlers.mouseUpEvent,!1);document.oncontextmenu=BCEngine.eventHandlers.rightClickEvent;document.addEventListener("DOMMouseScroll",BCEngine.eventHandlers.scrollEvent,!1);document.onmousewheel=BCEngine.eventHandlers.scrollEvent};
BCEngine.utils.ceilFoot=function(a){for(var c=[],b=1;5>=b;b++){if(a==BCEngine.cubeSize*b)return a/BCEngine.cubeSize;c.push(BCEngine.cubeSize*b)}for(var d,b=0,e=c.length;b<e;b++)if(a<c[b]){d=c[b];break}return d/BCEngine.cubeSize};BCEngine.utils.ceilHori=function(a){for(var c=[],b=1;16>=b;b++){if(a==BCEngine.cubeSize*b)return a/BCEngine.cubeSize;c.push(BCEngine.cubeSize*b)}for(var d,b=0,e=c.length;b<e;b++)if(a<c[b]){d=c[b];break}return d/BCEngine.cubeSize};
